# -*- coding: utf-8 -*-
"""Les 50 vidéos de la seconde vague : code, nom de fichier, titre du carton,
deux puces de solution, ligne de voix off."""

LIGNES = [
 ("T01","no-show","La table vide de 20 h",["ACOMPTE À LA RÉSERVATION","RAPPEL AUTOMATIQUE"],
  "Une table de six qui ne vient pas, un samedi soir. Avec FoodEatUp, le rappel part tout seul et l'acompte tient la réservation."),
 ("T02","liste-attente","La file sur le trottoir",["LISTE D'ATTENTE AU QR","SMS QUAND LA TABLE SE LIBÈRE"],
  "Vingt personnes debout dehors et personne pour tenir la liste. Avec FoodEatUp, chacun s'inscrit au QR code et reçoit un SMS quand sa table se libère."),
 ("T03","rotation-table","La table qui ne tourne pas",["TEMPS DE TABLE SUIVI","ROTATION MESURÉE"],
  "Deux heures pour un déjeuner, et trois tables perdues derrière. Avec FoodEatUp, vous voyez le temps de chaque table et la rotation de chaque service."),
 ("T04","acompte","L'annulation de la veille",["ACOMPTE EN LIGNE","CONDITIONS CLAIRES"],
  "Annulation à vingt-trois heures pour douze couverts. Avec FoodEatUp, l'acompte est encaissé à la réservation et les conditions sont écrites."),
 ("T05","evenement-prive","Le mariage de septembre",["DEVIS EN LIGNE","VALIDATION SIGNÉE"],
  "Un devis de groupe griffonné au dos d'une carte. Avec FoodEatUp, le devis part signé, chiffré, avec le menu et l'acompte."),
 ("T06","devis-groupe","Trente couverts d'entreprise",["MENU DE GROUPE","FACTURE AUTOMATIQUE"],
  "Trente couverts d'entreprise et une facture à refaire trois fois. Avec FoodEatUp, le devis devient commande, puis facture, sans ressaisie."),
 ("T07","terminal-paiement","Le terminal qui ne parle pas à la caisse",["PAIEMENT RATTACHÉ AU TICKET","RAPPROCHEMENT AUTOMATIQUE"],
  "Le terminal d'un côté, la caisse de l'autre, et l'écart à la fin. Avec FoodEatUp, chaque paiement se rattache à son ticket tout seul."),
 ("T08","pourboire","Le pourboire mal réparti",["POURBOIRES SUIVIS","RÉPARTITION TRANSPARENTE"],
  "Le pourboire de la semaine, et personne d'accord sur le partage. Avec FoodEatUp, il est enregistré, réparti et visible par l'équipe."),
 ("T09","tva","Trois taux de TVA",["TVA PAR PRODUIT","DÉCLARATION PRÊTE"],
  "Sur place, à emporter, alcool : trois taux et une seule tête. Avec FoodEatUp, la TVA est portée par le produit et la déclaration sort prête."),
 ("T10","marge","La marge qu'on ne voit pas",["MARGE PAR PLAT","TOP ET FLOP DU MOIS"],
  "Vous vendez plus et vous gagnez moins. Avec FoodEatUp, la marge se lit plat par plat, et les flops se voient avant la fin du mois."),
 ("T11","ticket-moyen","Le ticket moyen en baisse",["TICKET MOYEN SUIVI","VENTES ADDITIONNELLES PROPOSÉES"],
  "Le ticket moyen baisse et vous l'apprenez au bilan. Avec FoodEatUp, il est suivi chaque jour et la vente additionnelle est proposée en salle."),
 ("T12","depenses","Les notes de frais du dimanche",["DÉPENSES PHOTOGRAPHIÉES","CATÉGORISÉES PAR L'IA"],
  "Les tickets de courses dans la poche de la veste. Avec FoodEatUp, vous les photographiez et la dépense est classée toute seule."),
 ("T13","prix-fournisseur","Le beurre qui a doublé",["PRIX SUIVIS DANS LE TEMPS","ALERTE À LA HAUSSE"],
  "Le beurre a doublé et personne ne l'a vu passer. Avec FoodEatUp, chaque prix fournisseur est historisé et l'alerte tombe à la hausse."),
 ("T14","comparaison-fournisseur","Deux fournisseurs, un produit",["PRIX COMPARÉS","MEILLEUR CHOIX PROPOSÉ"],
  "Le même produit, deux fournisseurs, deux prix, et aucune comparaison. Avec FoodEatUp, la comparaison se fait à la ligne près."),
 ("T15","casse","Le carton tombé",["PERTES ENREGISTRÉES","MOTIF ET COÛT"],
  "Un carton qui tombe, et personne ne l'écrit nulle part. Avec FoodEatUp, la perte est saisie avec son motif et son coût."),
 ("T16","inventaire-tournant","L'inventaire du dimanche soir",["INVENTAIRE TOURNANT","QUELQUES LIGNES PAR JOUR"],
  "Quatre heures d'inventaire un dimanche soir. Avec FoodEatUp, l'inventaire devient tournant : quelques lignes par jour, et c'est juste."),
 ("T17","recette","La recette dans la tête du chef",["FICHE RECETTE PARTAGÉE","GRAMMAGES ET ÉTAPES"],
  "La recette est dans la tête du chef, et le chef est en congés. Avec FoodEatUp, la fiche recette est écrite, pesée, accessible au poste."),
 ("T18","production","La production du lendemain",["PLAN DE PRODUCTION","BASÉ SUR LES VENTES"],
  "Combien de fonds préparer pour demain ? Au feeling. Avec FoodEatUp, le plan de production sort des ventes réelles, pas du feeling."),
 ("T19","unites","Les kilos et les pièces",["UNITÉS CONVERTIES","PLUS D'ERREUR DE SAISIE"],
  "Le fournisseur livre en pièces, la recette compte en grammes. Avec FoodEatUp, la conversion est faite et le stock reste juste."),
 ("T20","cave","La cave qu'on ne compte plus",["CAVE INVENTORIÉE","ROTATION DES VINS"],
  "Trois bouteilles introuvables et un millésime oublié. Avec FoodEatUp, la cave est inventoriée et la rotation des vins se voit."),
 ("T21","happy-hour","L'happy hour à la tête du client",["HAPPY HOUR PROGRAMMÉE","PRIX APPLIQUÉS TOUT SEULS"],
  "L'happy hour appliquée à la tête du client, selon qui est au bar. Avec FoodEatUp, elle est programmée et les prix s'appliquent tout seuls."),
 ("T22","fidelite","La carte tamponnée perdue",["FIDÉLITÉ AU TÉLÉPHONE","POINTS QUI NE SE PERDENT PLUS"],
  "La carte à dix tampons, perdue au neuvième. Avec FoodEatUp, la fidélité vit dans le téléphone et les points ne se perdent plus."),
 ("T23","carte-cadeau","Le bon cadeau de Noël",["CARTES CADEAUX SUIVIES","SOLDE VÉRIFIÉ EN CAISSE"],
  "Un bon cadeau présenté en juin, émis en décembre, et introuvable. Avec FoodEatUp, la carte cadeau est suivie et son solde vérifié en caisse."),
 ("T24","jeu-concours","Le jeu concours sur un cahier",["ROUE DE LA FORTUNE","GAINS TRACÉS"],
  "Un tirage au sort dans un bocal, et deux gagnants pour un lot. Avec FoodEatUp, le jeu tourne en ligne et chaque gain est tracé."),
 ("T25","sondage","L'avis qu'on ne demande jamais",["SONDAGE APRÈS LE REPAS","RÉSULTATS CHIFFRÉS"],
  "Vous croyez savoir ce qu'ils ont pensé du service. Avec FoodEatUp, le sondage part après le repas et les résultats sont chiffrés."),
 ("T26","rfm","Le client qui n'est plus revenu",["SEGMENTS RFM","RELANCE AU BON MOMENT"],
  "Votre meilleur client n'est pas revenu depuis quatre mois. Avec FoodEatUp, le segment le signale et la relance part au bon moment."),
 ("T27","newsletter","La newsletter jamais envoyée",["NEWSLETTER PRÊTE","LISTE À JOUR"],
  "Une newsletter écrite en janvier, jamais partie. Avec FoodEatUp, elle est rédigée, la liste est à jour, et l'envoi est programmé."),
 ("T28","whatsapp","Le message du midi",["MODÈLES WHATSAPP VALIDÉS","ENVOI EN UN GESTE"],
  "Le plat du jour envoyé à trois groupes WhatsApp, à la main. Avec FoodEatUp, le modèle est validé et l'envoi part en un geste."),
 ("T29","site-web","Le site qui date de 2019",["SITE À JOUR","MENU SYNCHRONISÉ"],
  "Votre site affiche encore la carte de 2019. Avec FoodEatUp, le site suit la carte, et la carte suit la cuisine."),
 ("T30","click-collect","La commande à emporter au téléphone",["CLICK AND COLLECT","CRÉNEAU CHOISI PAR LE CLIENT"],
  "Prendre une commande à emporter en plein coup de feu. Avec FoodEatUp, le client commande en ligne et choisit son créneau."),
 ("T31","menu-qr","La carte plastifiée collante",["CARTE AU QR CODE","MODIFIÉE EN DIX SECONDES"],
  "Une carte plastifiée, collante, avec deux plats rayés au stylo. Avec FoodEatUp, la carte est au QR code et se modifie en dix secondes."),
 ("T32","photo-plat","Le plat sans photo",["PHOTOS SUR LA CARTE","PLATS MIS EN AVANT"],
  "Un plat que personne ne commande parce que personne ne l'imagine. Avec FoodEatUp, la photo est sur la carte et le plat repart."),
 ("T33","rupture-carte","Le plat plus disponible",["RUPTURE POUSSÉE EN SALLE","CARTE À JOUR EN TEMPS RÉEL"],
  "Le serveur vend un plat qu'il n'y a plus depuis deux heures. Avec FoodEatUp, la rupture remonte en salle dès qu'elle arrive."),
 ("T34","allergene-gluten","Le sans gluten qui ne l'est pas",["ALLERGÈNES SUR CHAQUE FICHE","CONTRÔLE AVANT ENVOI"],
  "Un sans gluten servi avec une sauce liée à la farine. Avec FoodEatUp, l'allergène est porté par l'ingrédient et remonte avant l'envoi."),
 ("T35","ddpp","Le rapport de la DDPP",["DOCUMENTS ARCHIVÉS","EXPORT DATÉ"],
  "Un rapport de la DDPP qui demande six mois de relevés. Avec FoodEatUp, tout est archivé et l'export sort daté."),
 ("T36","huile","L'huile de friture",["CONTRÔLE PROGRAMMÉ","CHANGEMENT TRACÉ"],
  "L'huile de friture changée quand quelqu'un y pense. Avec FoodEatUp, le contrôle est programmé et le changement est tracé."),
 ("T37","chambre-froide","La chambre froide qui monte",["SONDE SUIVIE","ALERTE LA NUIT"],
  "La chambre froide qui monte un dimanche, et la marchandise perdue. Avec FoodEatUp, la sonde alerte la nuit, avant la perte."),
 ("T38","reception-non-conforme","La livraison non conforme",["NON-CONFORMITÉ PHOTOGRAPHIÉE","AVOIR DEMANDÉ"],
  "Une palette non conforme acceptée parce qu'il fallait ouvrir. Avec FoodEatUp, la non-conformité est photographiée et l'avoir demandé."),
 ("T39","contrat","Le contrat jamais signé",["CONTRATS GÉNÉRÉS","SIGNATURE SUIVIE"],
  "Un extra qui travaille depuis trois semaines sans contrat signé. Avec FoodEatUp, le contrat est généré et la signature suivie."),
 ("T40","documents-employe","La carte de séjour expirée",["DOCUMENTS SUIVIS","ALERTE AVANT ÉCHÉANCE"],
  "Un document d'employé expiré depuis un mois, découvert au contrôle. Avec FoodEatUp, l'échéance est suivie et l'alerte tombe avant."),
 ("T41","conges","Le congé accordé deux fois",["DEMANDES CENTRALISÉES","VALIDATION TRACÉE"],
  "Un congé accordé à l'oral, oublié, puis accordé à un autre. Avec FoodEatUp, la demande est écrite, validée, et visible du planning."),
 ("T42","heures-supplementaires","Les heures qui débordent",["HEURES COMPTÉES","ALERTE AVANT LE SEUIL"],
  "Douze heures supplémentaires découvertes à la paie. Avec FoodEatUp, les heures sont comptées au fil de l'eau et l'alerte tombe avant le seuil."),
 ("T43","onboarding","Le premier jour de l'extra",["PARCOURS D'ARRIVÉE","POSTES ET RÈGLES EXPLIQUÉS"],
  "Un extra qui arrive et personne pour lui montrer le poste. Avec FoodEatUp, le parcours d'arrivée est prêt avant qu'il pousse la porte."),
 ("T44","formation-haccp","La formation qu'on repousse",["FORMATIONS SUIVIES","ATTESTATIONS ARCHIVÉES"],
  "La formation hygiène repoussée depuis deux ans. Avec FoodEatUp, elle est planifiée, suivie, et l'attestation est archivée."),
 ("T45","caroline","La ligne toujours occupée",["CAROLINE RÉPOND","24 HEURES SUR 24"],
  "Le téléphone sonne pendant que vous dressez douze assiettes. Avec FoodEatUp, Caroline répond, prend la réservation, et vous continuez."),
 ("T46","jarvis","Les mains prises",["JARVIS ÉCOUTE","COMMANDE À LA VOIX"],
  "Les deux mains dans la pâte et une sortie de stock à saisir. Avec FoodEatUp, Jarvis écoute et enregistre pendant que vous travaillez."),
 ("T47","predibot","La nuit qui ne sert à rien",["PREDIBOT PRÉPARE LA NUIT","COMMANDES PROPOSÉES AU MATIN"],
  "Vous fermez à minuit et vous rouvrez à sept heures. Avec FoodEatUp, PrediBot travaille entre les deux et propose les commandes au matin."),
 ("T48","iris","La page qui ne bouge plus",["IRIS PUBLIE","POUR LE RESTAURANT"],
  "Votre page n'a rien publié depuis trois semaines. Avec FoodEatUp, Iris publie pour le restaurant, tous les jours, à l'heure."),
 ("T49","multi-etablissement","Deux adresses, deux vérités",["MULTI-ÉTABLISSEMENT","UN SEUL TABLEAU DE BORD"],
  "Deux adresses, deux logiciels, deux vérités le soir. Avec FoodEatUp, les deux sont sur le même tableau de bord."),
 ("T50","une-app","Sept logiciels, sept factures",["UNE SEULE APPLICATION","UNE SEULE FACTURE"],
  "Sept logiciels, sept abonnements, sept mots de passe. Avec FoodEatUp, c'est une seule application, et une seule facture."),
]
