# -*- coding: utf-8 -*-
"""Troisième vague : 60 vidéos. Code, nom de fichier, titre du carton,
deux puces de solution, ligne de voix off."""

LIGNES = [
 ("U01","matin","Sept heures du matin",["LE POINT DU JOUR SUR WHATSAPP","AVANT D'OUVRIR"],
  "Sept heures, vous ouvrez et vous ne savez pas encore ce que la journée demande. Avec FoodEatUp, PrediBot vous a déjà envoyé le point du jour."),
 ("U02","coup-de-feu","Midi moins dix",["COMMANDES ROUTÉES","CHAQUE POSTE SAIT"],
  "Midi moins dix, quarante couverts annoncés et un ticket illisible. Avec FoodEatUp, chaque plat part au bon poste, dans le bon ordre."),
 ("U03","service-du-soir","Dix-neuf heures quarante",["SALLE ET CUISINE SYNCHRONES","RIEN NE SE PERD"],
  "Dix-neuf heures quarante, la salle est pleine et la cuisine ne suit plus. Avec FoodEatUp, la salle et la cuisine voient la même chose."),
 ("U04","fermeture-caisse","Minuit et demi",["CLÔTURE EN UN GESTE","RAPPORT ENVOYÉ"],
  "Minuit et demi, tout le monde est parti et la caisse ne tombe pas juste. Avec FoodEatUp, la clôture se fait en un geste et le rapport part tout seul."),
 ("U05","lundi","Le lundi de relâche",["SEMAINE PRÉPARÉE","COMMANDES PROPOSÉES"],
  "Le lundi, fermé, et pourtant vous travaillez. Avec FoodEatUp, la semaine se prépare pendant que vous vous reposez."),
 ("U06","samedi","Le samedi à deux services",["DOUBLE SERVICE PLANIFIÉ","PERSONNE EN TROP, PERSONNE EN MOINS"],
  "Un samedi à deux services et une équipe mal calée. Avec FoodEatUp, le planning suit l'activité prévue, service par service."),
 ("U07","dimanche","Le brunch du dimanche",["RÉSERVATIONS EN LIGNE","MENU BRUNCH À PART"],
  "Le brunch du dimanche, complet, et trois familles refusées par téléphone. Avec FoodEatUp, tout se réserve en ligne, même le brunch."),
 ("U08","ete","L'été, la terrasse pleine",["TERRASSE AU PLAN DE SALLE","MÉTÉO PRISE EN COMPTE"],
  "Trente degrés, la terrasse pleine, et la salle vide. Avec FoodEatUp, la terrasse est au plan de salle et la météo entre dans la prévision."),
 ("U09","fetes","Le mois de décembre",["MENUS DE FÊTES","GROUPES ET ACOMPTES"],
  "Décembre, les repas d'entreprise, et un carnet qui déborde. Avec FoodEatUp, les groupes réservent, signent et versent l'acompte en ligne."),
 ("U10","creux","Le mardi creux",["CAMPAGNE CIBLÉE","REMPLIR LE CREUX"],
  "Le mardi soir, douze couverts et six personnes en salle. Avec FoodEatUp, une campagne ciblée remplit le creux avant qu'il arrive."),
 ("U11","pizzeria","La pizzeria du coin",["COMMANDE EN LIGNE SANS COMMISSION","FOUR ET LIVRAISON SUIVIS"],
  "Une pizzeria qui vit sur les plateformes et paie trente pour cent. Avec FoodEatUp, la commande passe par votre site, sans commission."),
 ("U12","boulangerie","La boulangerie à six heures",["PRODUCTION CALCULÉE","INVENDUS EN BAISSE"],
  "Vingt baguettes invendues chaque soir, depuis toujours. Avec FoodEatUp, la production se calcule sur les ventes réelles."),
 ("U13","food-truck","Le food truck",["CAISSE MOBILE","STOCK DANS LA POCHE"],
  "Un camion, deux services, aucune visibilité sur le stock. Avec FoodEatUp, la caisse et le stock tiennent dans le téléphone."),
 ("U14","brasserie","La brasserie de cent couverts",["CENT COUVERTS TENUS","ROTATION SUIVIE"],
  "Cent couverts au déjeuner et personne pour tenir le rythme des tables. Avec FoodEatUp, la rotation se suit table par table."),
 ("U15","dark-kitchen","La cuisine sans salle",["MULTI-CANAL RÉUNI","UN SEUL ÉCRAN CUISINE"],
  "Quatre plateformes, quatre tablettes, un seul cuisinier. Avec FoodEatUp, tout arrive sur le même écran cuisine."),
 ("U16","traiteur","Le traiteur du week-end",["DEVIS ET PRODUCTION LIÉS","FICHES DE FABRICATION"],
  "Un buffet pour cent personnes calculé sur un coin de table. Avec FoodEatUp, le devis devient la fiche de production."),
 ("U17","bar-a-vin","Le bar à vin",["CAVE SUIVIE","VERRE ET BOUTEILLE DISTINGUÉS"],
  "Un vin au verre servi à la louche et une marge qui disparaît. Avec FoodEatUp, le verre et la bouteille sont suivis séparément."),
 ("U18","gastronomique","La table gastronomique",["FICHES TECHNIQUES PRÉCISES","ALLERGIES AU GRAMME"],
  "Un menu en sept services et une allergie annoncée à la dernière minute. Avec FoodEatUp, chaque service porte ses allergènes."),
 ("U19","cantine","La cantine d'entreprise",["FLUX GÉRÉ","PRÉVISION AU COUVERT"],
  "Trois cents repas en cinquante minutes, et une file qui déborde. Avec FoodEatUp, la prévision et la commande à l'avance absorbent le flux."),
 ("U20","plusieurs-adresses","Le deuxième restaurant",["DEUX ADRESSES, UN OUTIL","COMPARAISON À LA LIGNE"],
  "Le deuxième restaurant a ouvert, et vous avez perdu le premier de vue. Avec FoodEatUp, les deux se pilotent depuis le même écran."),
 ("U21","trop-cher","« C'est trop cher »",["MOINS CHER QUE SEPT OUTILS","UNE SEULE FACTURE"],
  "Vous trouvez un logiciel de gestion trop cher. Comptez ce que coûtent les sept que vous payez déjà, plus les erreurs."),
 ("U22","pas-le-temps","« Je n'ai pas le temps »",["CONFIGURATION GUIDÉE","QUARANTE-CINQ MINUTES"],
  "Vous n'avez pas le temps d'installer un logiciel. C'est justement pour ça : quarante-cinq minutes de configuration, guidées, une seule fois."),
 ("U23","equipe-suivra-pas","« Mon équipe ne suivra pas »",["UN QR CODE PAR POSTE","RIEN À APPRENDRE"],
  "Vous pensez que votre équipe ne suivra pas. Un QR code par poste, trois boutons, et personne n'a rien à apprendre."),
 ("U24","deja-equipe","« Je suis déjà équipé »",["VOS OUTILS RÉUNIS","REPRISE DE VOS DONNÉES"],
  "Vous êtes déjà équipé : une caisse, un stock, un planning, et rien qui se parle. FoodEatUp les réunit, et reprend vos données."),
 ("U25","papier","« Le papier me suffit »",["LE PAPIER NE SE CHERCHE PLUS","EXPORT EN UN CLIC"],
  "Le papier vous suffit, jusqu'au jour où il faut retrouver un relevé de mars. Avec FoodEatUp, c'est une recherche, pas une journée."),
 ("U26","confiance-ia","« L'IA, je n'y crois pas »",["L'IA PROPOSE, VOUS DÉCIDEZ","TOUT EST TRAÇABLE"],
  "L'IA vous laisse sceptique. Ici, elle propose et vous décidez : chaque action est écrite, datée, et vous pouvez la refuser."),
 ("U27","donnees","« Et mes données ? »",["HÉBERGEMENT EN EUROPE","VOS DONNÉES VOUS APPARTIENNENT"],
  "Vos données vous inquiètent, et vous avez raison. Elles sont hébergées en Europe, elles vous appartiennent, et vous les exportez quand vous voulez."),
 ("U28","migration","Le jour de la bascule",["REPRISE ACCOMPAGNÉE","AUCUN SERVICE ARRÊTÉ"],
  "Changer de logiciel un jour de service, personne n'en a envie. La bascule se fait accompagnée, sans arrêter un seul service."),
 ("U29","support","Le samedi soir, personne au bout du fil",["ASSISTANCE QUAND VOUS TRAVAILLEZ","RÉPONSE EN SERVICE"],
  "Un problème un samedi à vingt heures, et un support ouvert du lundi au vendredi. Nous, on travaille quand vous travaillez."),
 ("U30","essai","Le premier soir",["ESSAI GRATUIT","SANS CARTE BANCAIRE"],
  "Vous voulez voir avant de payer. Essayez un service entier, gratuitement, sans carte bancaire."),
 ("U31","caroline-nuit","Vingt-trois heures, ça sonne",["CAROLINE PREND L'APPEL","LA TABLE EST RÉSERVÉE"],
  "Vingt-trois heures, le téléphone sonne, le restaurant est fermé. Caroline décroche et la table de demain est réservée."),
 ("U32","caroline-langues","Un client qui ne parle pas français",["CAROLINE PARLE PLUSIEURS LANGUES","LA COMMANDE EST JUSTE"],
  "Un client au téléphone, et pas un mot de français des deux côtés. Caroline parle sa langue et la commande est juste."),
 ("U33","jarvis-temperature","Les mains dans la chambre froide",["RELEVÉ DICTÉ","HORODATÉ TOUT SEUL"],
  "Un relevé de température à noter, les mains pleines et gelées. Vous le dictez à Jarvis et il est horodaté."),
 ("U34","jarvis-tache","La tâche qu'on oublie",["TÂCHES ASSIGNÉES","VALIDÉES PAR PHOTO"],
  "La tâche donnée à l'oral au début du service, oubliée à la fin. Jarvis la porte, la rappelle et la fait valider."),
 ("U35","predibot-commande","La commande du jeudi",["BESOIN CALCULÉ","BON DE COMMANDE PRÊT"],
  "La commande du jeudi passée de tête, avec deux oublis. PrediBot calcule le besoin et prépare le bon."),
 ("U36","predibot-alerte","L'alerte avant la casse",["SEUILS SURVEILLÉS","ALERTE AVANT LA RUPTURE"],
  "La rupture, vous l'apprenez toujours en plein service. PrediBot la voit venir la veille."),
 ("U37","iris-post","La publication du jour",["POST PRÊT CHAQUE MATIN","À PARTIR DE VOS VRAIES DONNÉES"],
  "Publier tous les jours, personne n'a le temps. Iris écrit le post du matin à partir de ce que vous avez vraiment vendu."),
 ("U38","iris-avis","La réponse à l'avis",["RÉPONSE PROPOSÉE","VOUS VALIDEZ"],
  "Un avis à une étoile qui reste sans réponse pendant trois semaines. Iris propose la réponse, vous la validez."),
 ("U39","claude","Parler à son restaurant",["PILOTAGE EN LANGAGE NATUREL","177 OUTILS BRANCHÉS"],
  "Demander à votre logiciel ce qui s'est vendu hier, en français, comme à un collègue. C'est le principe."),
 ("U40","configuration","Les quarante-cinq premières minutes",["CONFIGURATION GUIDÉE","MODULE OFFERT"],
  "Configurer un restaurant entier, on croit que ça prend des semaines. Comptez quarante-cinq minutes, guidées."),
 ("U41","boucle-gestion","La boucle gestion",["CONFIG, ÉQUIPE, STOCK, HACCP","QUATRE ÉTAPES QUI SE TIENNENT"],
  "Configuration, équipe, stock, HACCP : quatre étapes qui ne se parlent jamais. Ici, elles forment une boucle."),
 ("U42","boucle-vente","La boucle vente",["E-COMMERCE, COMM, FIDÉLITÉ, COMPTA","LA SECONDE BOUCLE"],
  "Vendre, communiquer, fidéliser, compter : la deuxième boucle, celle qu'on néglige toujours."),
 ("U43","huit","Le signe du huit",["DEUX BOUCLES QUI SE CROISENT","UN SEUL LOGICIEL"],
  "Un restaurant, c'est deux boucles qui se croisent. Le point de croisement, c'est votre logiciel."),
 ("U44","chef-fondateur","Écrit par un cuisinier",["PENSÉ EN CUISINE","PAS EN OPEN SPACE"],
  "Ce logiciel n'a pas été pensé dans un open space. Il a été pensé derrière un piano, pendant vingt ans."),
 ("U45","erreur-saisie","La double saisie",["SAISI UNE FOIS","REPRIS PARTOUT"],
  "La même information saisie dans la caisse, dans le stock, puis dans la compta. Ici, on la saisit une fois."),
 ("U46","export-comptable","Le dossier pour l'expert-comptable",["EXPORT COMPTABLE PRÊT","CHAQUE MOIS"],
  "Le carton de justificatifs déposé chez le comptable en avril. Avec FoodEatUp, l'export part chaque mois, complet."),
 ("U47","cloture-mensuelle","La clôture du mois",["CHIFFRES CONSOLIDÉS","ÉCARTS EXPLIQUÉS"],
  "La clôture du mois faite trois semaines trop tard. Avec FoodEatUp, les chiffres sont consolidés le premier du mois."),
 ("U48","tresorerie","La trésorerie du 15",["ENCAISSEMENTS ET DÉPENSES","VUE À TRENTE JOURS"],
  "Le quinze du mois, vous ne savez pas si le mois passe. Avec FoodEatUp, vous voyez trente jours devant."),
 ("U49","banque","Le rendez-vous à la banque",["CHIFFRES À JOUR","DOSSIER EXPORTABLE"],
  "Un rendez-vous à la banque avec des chiffres de l'an dernier. Avec FoodEatUp, le dossier sort à jour, en un export."),
 ("U50","assurance","Le sinistre du congélateur",["RELEVÉS HORODATÉS","PREUVE POUR L'ASSURANCE"],
  "Un congélateur en panne, et une assurance qui demande des preuves. Vos relevés horodatés sont la preuve."),
 ("U51","hygiene-note","La note d'hygiène affichée",["CONTRÔLES TENUS","NOTE DÉFENDUE"],
  "Une note d'hygiène affichée sur votre vitrine, vue par tout le quartier. Tenez vos contrôles et elle ne bougera pas."),
 ("U52","photo-controle","La photo du contrôleur",["PREUVES PHOTO ARCHIVÉES","DATÉES ET SIGNÉES"],
  "Le contrôleur photographie, vous, vous n'avez rien. Avec FoodEatUp, chaque contrôle laisse sa photo, datée et signée."),
 ("U53","staff-turnover","L'extra qui ne revient pas",["POSTES DOCUMENTÉS","REMPLAÇANT OPÉRATIONNEL"],
  "Un extra formé pendant deux semaines qui ne revient pas. Avec FoodEatUp, le poste est documenté et le suivant démarre plus vite."),
 ("U54","planning-envoye","Le planning envoyé le samedi",["PLANNING PUBLIÉ À L'AVANCE","CHACUN LE VOIT"],
  "Le planning de la semaine envoyé le samedi soir, par message. Avec FoodEatUp, il est publié à l'avance et chacun le voit."),
 ("U55","absence","L'absence de dernière minute",["REMPLACEMENT PROPOSÉ","ÉQUIPE PRÉVENUE"],
  "Un arrêt à sept heures du matin pour un service à midi. Avec FoodEatUp, le remplacement est proposé et l'équipe est prévenue."),
 ("U56","client-fidele","Le client qui revient",["HISTORIQUE COMPLET","ATTENTION AU BON MOMENT"],
  "Un client qui vient chaque semaine depuis deux ans, et personne ne le sait. Avec FoodEatUp, son historique est là, et l'attention aussi."),
 ("U57","anniversaire","L'anniversaire oublié",["DATES SUIVIES","INVITATION AUTOMATIQUE"],
  "L'anniversaire d'un habitué, oublié pour la troisième année. Avec FoodEatUp, l'invitation part toute seule."),
 ("U58","parrainage","Le bouche-à-oreille",["PARRAINAGE SUIVI","RÉCOMPENSE AUTOMATIQUE"],
  "Le bouche-à-oreille marche, et vous ne savez pas qui l'a lancé. Avec FoodEatUp, le parrainage est suivi et récompensé."),
 ("U59","google","La fiche Google incomplète",["FICHE À JOUR","HORAIRES ET MENU SYNCHRONISÉS"],
  "Votre fiche Google affiche des horaires de l'an dernier. Avec FoodEatUp, elle suit vos horaires et votre carte."),
 ("U60","demain","Demain matin",["DÉMARREZ CE SOIR","OPÉRATIONNEL DEMAIN"],
  "Demain matin, vous rouvrez. La question n'est pas de savoir si vous avez le temps, mais combien vous en perdez encore."),
]
