import json
# côté = "chaos" (subit) | "maitrise" (tient) | "duel"
# theme = mots-clés des paroles que le plan peut servir
CAT = {
 # --- catalogue Social FoodEatUp (9:16 natif) ---
 "EP021":("chaos","Chef contre imprimante","imprimante,ticket"),
 "EP008":("chaos","La pile de tickets","ticket,pile"),
 "EP083":("chaos","Le cri dans le vide","cri,burgers,bruit"),
 "EP013":("chaos","L'avalanche de notifications","alarmes,applis,notifications"),
 "EP031":("chaos","L'avalanche de tupperware","tupperware,etiquette,dlc"),
 "EP045":("chaos","La chambre froide","pompier,enferme,personne"),
 "EP038":("chaos","Le chariot fou","courses,reappro"),
 "EP064":("chaos","Le planning au marqueur","planning,marqueur,ratures"),
 "EP088":("chaos","Une étoile","avis,etoile,poussiere"),
 "EP015":("chaos","La tour d'assiettes","empile,ecroulement,debout"),
 "EP022":("chaos","La facture qui fait pleurer","dix,logiciels,facture"),
 "EP029":("chaos","Les douze assiettes","empile,assiettes"),
 "EP037":("chaos","Le dormeur debout","tete,fatigue,nuit"),
 "EP044":("chaos","Les six stylos","ratures,stylo,commande"),
 "EP050":("chaos","La casserole brûlante","chauffe,brule"),
 "EP059":("chaos","L'ardoise","mensonge,ardoise,com"),
 "EP061":("chaos","Le badge introuvable","pointage,badge"),
 "EP063":("chaos","Le post-it perdu","conge,samedi,papier"),
 "EP069":("chaos","Le livreur fantôme","livraison,reception"),
 "EP076":("chaos","Le recomptage","compte,deux fois,inventaire"),
 "EP080":("chaos","Le tiroir vide","caisse,encaisse"),
 "EP087":("chaos","Les trois tablettes","applis,ecrans,plateformes"),
 "EP091":("chaos","Le pétard dans le tiramisu","imprevu,surprise"),
 "EP099":("chaos","Le répondeur préhistorique","client,ailleurs,appels"),
 "EP108":("chaos","Le poulpe du pass","passe,plein,bras"),
 "EP111":("chaos","L'imprimante 3D qui déraille","imprimante,deraille"),
 "EP112":("chaos","Le casque de réalité augmentée","gadget,carte"),
 "EP119":("chaos","La mascotte poulet et le vent","tracts,vent,marketing"),
 "EP125":("chaos","Le client qui refait le plan de salle","salle,plan,client"),
 "EP130":("chaos","Fête de la musique","salle pleine,rue"),
 "EP131":("chaos","Rentrée, deux absents","samedi,absents,planning"),
 "EP141":("maitrise","Cuisine, cockpit spatial","table six,vingt-deux minutes,ecrit"),
 "EP103":("maitrise","Le car de 40","quarante couverts,debarquent"),
 "EP128":("maitrise","Saint-Valentin surbookée","postes,salle,cordeau"),
 "EP143":("maitrise","La commande de 200 pièces","sorti ce qu'il fallait,anticipe"),
 "EP144":("maitrise","Le procès du steak","proces,dossier,plaignant"),
 "EP100":("maitrise","L'influenceur au ring light","ring light,poste"),
 "EP114":("maitrise","La choré pendant que ça brûle","poste,encaisse,brigade"),
 "EP067":("maitrise","Le thermomètre humain","frigo,releve,temperature"),
 "EP072":("maitrise","Le classeur","classeur,vendredi,historique"),
 "EP122":("maitrise","« Comme d'habitude »","clients par coeur,habitude"),
 "EP093":("maitrise","Le chef part à la pêche","anticipe,mains libres"),
 "EP129":("maitrise","Premier jour de terrasse","salle,terrasse,tourne"),
 "EP142":("duel","Duel à la spatule","pont,spatules,assiette"),
 # --- bibliothèque locale déjà générée (16:9 sauf 25→28) ---
 "hf2-01-six-heures":("maitrise","Six heures du matin","matin,calme"),
 "hf2-03-declic":("maitrise","Le déclic","declic,decide"),
 "hf2-04-cuisine-salle":("maitrise","Cuisine et salle","cuisine,salle"),
 "hf2-05-fin-service":("maitrise","Fin de service","ferme,file"),
 "hf2-06-marque":("maitrise","La marque","marque"),
 "hf2-07-client-salle":("maitrise","Client en salle","client,salle"),
 "hf2-08-tracabilite":("maitrise","Traçabilité","date,ecrite,tracabilite"),
 "hf2-09-fermeture-salle":("maitrise","Fermeture de salle","ferme,minuit"),
 "hf2-10-notification-depart":("maitrise","Notification au départ","previens,avance"),
 "hf2-11-chef-plan-sequence":("maitrise","Chef, plan-séquence","chef,calme,passe"),
 "hf2-14-chef-apres-service":("maitrise","Chef après le service","leve les yeux,apres"),
 "hf2-15-couloir-traversee":("maitrise","Traversée du couloir","traverse,rue"),
 "hf2-16-salle-prete":("maitrise","La salle prête","salle prete,avance"),
 "hf2-17-salle-service-soir":("maitrise","Salle en service, le soir","soir,salle,service"),
 "hf2-18-salle-apres-midi":("maitrise","Salle l'après-midi","apres-midi,calme"),
 "hf2-19-serveur-fermeture":("maitrise","Serveur à la fermeture","ferme,soiree"),
 "hf2-20-directeur-dashboard":("maitrise","Directeur, tableau de bord","ecrit,savait,avance"),
 "hf2-21-chef-tablette":("maitrise","Chef à la tablette","affiche,attend,tablette"),
 "hf2-27-scan-etagere":("maitrise","Scan de l'étagère","scan,stock,releve"),
 "hf2-28-pouce-nuit":("maitrise","Le pouce, la nuit","gagne,soiree,minuit"),
 "hf2-02-trois-ecrans":("chaos","Trois écrans","ecrans,applis"),
 "hf2-12-tickets-rail":("chaos","Le rail à tickets","ticket,rail,bande"),
 "hf2-13-cuisine-vide-nuit":("chaos","Cuisine vide, la nuit","nuit,vide,minuit"),
 "hf2-22-notifications-desordre":("chaos","Notifications en désordre","alarmes,notifications"),
 "hf2-23-classeur-poussiereux":("chaos","Le classeur poussiéreux","classeur,poussiere,vendredi"),
 "hf2-24-chambre-froide":("chaos","Chambre froide","frigo,froide"),
 "hf2-25-reserve-immobile":("chaos","La réserve immobile","reserve,stock,immobile"),
 "hf2-26-comptage-recommence":("chaos","Le comptage qui recommence","compte,deux fois,recommence"),
 "hero-brigade-deux-langues":("maitrise","La brigade, deux langues","brigade,poste"),
 "hero-caisse-ticket-z":("maitrise","Caisse, ticket Z","encaisse,compte,ferme"),
 "hero-chef-carnet-dlc":("chaos","Chef, carnet DLC papier","dlc,carnet,papier"),
 "hero-chef-scan-carton":("maitrise","Chef, scan du carton","scan,reception,releve"),
 "hero-cloche-passe":("chaos","La cloche du passe","cloche,passe,bruit"),
 "hero-cuisine-vide-matin":("maitrise","Cuisine vide au matin","matin,calme,savait"),
 "hero-directeur-bureau-matin":("maitrise","Directeur, bureau le matin","matin,savait,lundi"),
 "hero-directeur-sept-onglets":("chaos","Directeur, sept onglets","onglets,applis,dix"),
 "hero-fermeture-lumieres":("maitrise","Extinction des lumières","ferme,file,soiree"),
 "hero-kds-mural":("maitrise","KDS mural","affiche,poste,plat"),
 "hero-portrait-chef":("maitrise","Portrait du chef","chef,regard,face"),
 "hero-salle-vide-matin":("maitrise","Salle vide au matin","matin,vide,avance"),
 "hero-serveur-place-client":("maitrise","Le serveur place le client","client,table,place"),
 "hero-serveur-plan-table":("maitrise","Serveur, plan de table","plan,table,poste"),
 "hero-serveur-trois-tablettes":("chaos","Serveur, trois tablettes","tablettes,applis,dix"),
}
json.dump(CAT, open("work/catalogue.json","w"), ensure_ascii=False, indent=1)
n_c=sum(1 for v in CAT.values() if v[0]=="chaos"); n_m=sum(1 for v in CAT.values() if v[0]=="maitrise")
print(f"{len(CAT)} plans sources : {n_c} chaos, {n_m} maîtrise, 1 duel")
print(f"→ 4 fenêtres par plan = {len(CAT)*4} segments visuels distincts disponibles")
